server:
  port: 8080

spring:
  application:
    name: dubai-multitrade-poc
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:change-me@example.com}
    password: ${MAIL_PASSWORD:change-me}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
